// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7PNwYBMMVNaSlIoWiunsgQ_uszuqL2Y',
    appId: '1:851284711758:android:00b83ba61b45cdf80b261f',
    messagingSenderId: '851284711758',
    projectId: 'ablecredit-anish',
    databaseURL: 'https://ablecredit-anish-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ablecredit-anish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAImcys0oKoYLFOx_1ySUlc78hsxF3-VwI',
    appId: '1:851284711758:ios:c69eab495ec71f5f0b261f',
    messagingSenderId: '851284711758',
    projectId: 'ablecredit-anish',
    databaseURL: 'https://ablecredit-anish-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ablecredit-anish.firebasestorage.app',
    iosBundleId: 'com.example.ablecredit',
  );
}
